version: '3.8'

services:
  nginx:
    image: nginx:1.23
    ports:
      - "${PORT}:80"
    volumes:
      - "./nginx/site.conf:/etc/nginx/conf.d/default.conf"
      - "../public:/app/public:ro"
    command: ['nginx', '-g', 'daemon off;']
  php:
    build: php
    working_dir: /app/bin
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - "../:/app:ro"
      - "../data:/app/data"
