version: '3'

services:
  php:
    environment:
      - ASYNC=1
    build: ./php
    working_dir: /app/public
    volumes:
      - "../:/app"
    ports:
      - "${PORT}:80"
    command: ['php', 'index.php']